name: Auto Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_USER }}
        username: ${{ secrets.KUMARAN_EC2 }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull your-dockerhub-username/devops-app
          docker stop devops-app || true
          docker rm devops-app || true
          docker run -d -p 80:5000 --name devops-app your-dockerhub-username/devops-apip
